---
# tasks file for master
- name: put bridge service
  template:
    src: roles/master/templates/bridge.service.j2
    dest: /etc/systemd/system/bridge.service
    mode: 0755

- name: run bridge service
  service:
    name: bridge
    state: started

- name: systemd daemon reload
  shell: systemctl daemon-reload


- name: enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: restarted
