---
- hosts: localhost
  connection: local
  vars:
      contents: "{{ lookup('vault_lookup', '/etc/foo.txt') }}"

  tasks:

      - debug:
          msg: the value of foo.txt is {{ contents }} as seen today {{ lookup('pipe', 'date +"%Y-%m-%d"') }}
  