---
- hosts:
    - lbs
    - backends
  user: vagrant
  become: yes
  roles:
    - disable-selinux  

- hosts: lbs
  user: vagrant
  become: true
  roles:
    - haproxy_role

- hosts: backends
  user: vagrant
  become: true
  roles:
    - backend_role
