# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  (0..2).each do |i|
    config.vm.define "box#{i}" do |box|
      box.vm.network "private_network", ip: "192.168.33.1#{i}"
      box.vm.hostname = "box#{i}"
      config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      box.vm.provision :shell do |shell|
        shell.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        SHELL
      end
    end
  end
end