---
# tasks file for common
- name: yum update
  yum:
    name: '*'
    state: latest

- name: add kubernetes repo
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg # https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: yes

- name: add docker ce stable
  yum_repository:
    name: docker-ce
    description: docker cd repo
    baseurl:
      - https://download.docker.com/linux/centos/7/x86_64/stable
      - https://download.docker.com/linux/centos/7/x86_64/edge
      - https://download.docker.com/linux/centos/7/x86_64/test
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
#
#- name: add older docker version repo
#  yum_repository:
#    name: dockerrepo
#    description: dockerrepo
#    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
#    gpgcheck: yes
#    gpgkey: https://yum.dockerproject.org/gpg
#
- name: install docker
  yum:
    #name: docker-engine-17.05.0.ce-1.el7.centos
    name: docker-ce
    state: installed

- name: enable docker
  service:
    name: docker
    enabled: yes
    state: started

- name: disable selinux
  command: setenforce 0
  ignore_errors: yes
  become: yes

- name: install kubeadm
  yum:
    name: kubeadm
    state: latest

- name: install kubectl
  yum:
    name: kubectl
    state: latest

- name: install kubelet
  yum:
    name: kubelet
    state: latest

- name: iptables bridge-nf set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes

- name: swap off
  shell: swapoff /dev/mapper/centos-swap
