---
jenkins_version: 2.221
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_java_options: "-Xmx2048m -Xms2048m -Djenkins.install.runSetupWizard=false -Dfile.encoding=UTF8"

jenkins_plugins:
  - configuration-as-code
  - job-dsl
  - git
  - rebuild
  - docker-workflow
  - cloudbees-folder
  - workflow-job
  - workflow-multibranch
  - timestamper
  - ssh-agent
  - s3
  - golang
  - credentials-binding
  - config-file-provider
  - pipeline-npm
  - nodejs
    
jenkins_plugins_state: present
jenkins_plugin_timeout: 60

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

### Swap-off
swap_file_state: absent
