SSH_PRIVATE_KEY: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAQEAxQC+Ka6D3yth7QiMpTtVVB8T0KKIbn9kgg7aZ7gpf4n7uyvsm5VY
  cdYGTMkDsR9KhUf3xPKsBLoDwasZTtXSN0aoUsou4nnYX4YQWudvOGVipdzZ4zfAlYKEi9
  cFY4yQayJmysG7OzVjcGBrPA3RZ9ltoxVhrvuJgcSFTC8GAMVkqUzCYb55E0yOeL5tpPSu
  BfP+62FcZ+qTgJ8LF2ehOzAFugwc9usFX9qYx4qeOAkua27J8R4UUMNERnrTNzc8AXDfdE
  7lofWFoMPyiK3XPV8jKKNxvddnJ1mlDY6miIakadMg4E1+/9+NikqWiYxwZOnBntz89I1K
  4udhUjp92wAAA8DC6UG/wulBvwAAAAdzc2gtcnNhAAABAQDFAL4proPfK2HtCIylO1VUHx
  PQoohuf2SCDtpnuCl/ifu7K+yblVhx1gZMyQOxH0qFR/fE8qwEugPBqxlO1dI3RqhSyi7i
  edhfhhBa5284ZWKl3NnjN8CVgoSL1wVjjJBrImbKwbs7NWNwYGs8DdFn2W2jFWGu+4mBxI
  VMLwYAxWSpTMJhvnkTTI54vm2k9K4F8/7rYVxn6pOAnwsXZ6E7MAW6DBz26wVf2pjHip44
  CS5rbsnxHhRQw0RGetM3NzwBcN90TuWh9YWgw/KIrdc9XyMoo3G912cnWaUNjqaIhqRp0y
  DgTX7/342KSpaJjHBk6cGe3Pz0jUri52FSOn3bAAAAAwEAAQAAAQAynJc+VCRzAE0/PVQM
  2yp32ygXELqmULo8o54+yVR3/LYchxNZgUvgqxChR39YUOavSScBhSrmZ/exGMj+tPY110
  RFSMY0zwLkv6eSAyVSwtFONWgQ9PDYOFjfKFWtFp6/t23bJ1x3wKaUZ2EFY7Npz7VYEZUw
  BFV2bkukn+wV5Cz0qX47X9vECKJRkiev5pXf/Lqr67TUG6s4djz+wWe4HOTW9oaU+NG41t
  8uIprdPPWjxr/t2KP2pjSP4dgmzr3SQKGgFTuPz15SdZBh6sHdxrEAfr9Fkg1SaLy74Yl2
  80ZRcvQPp3IayQ62GikyGSoZDRYKpYcQo8N6Eh26VNehAAAAgQDZLAz1FBomEaF5LXZquV
  lkOttp/nV6f7n6y0nx0WjEqFAUvkelAMYXMa0mkYhL+gV0YpX+OndCPQKzEcHZyMDaKpRb
  A4YJbncPOT1j9i+OgMnhhYoFp2b4t/r1ReQZh36WwsMMisPbf2AGLXuilcricUkyuYo7HB
  CIF6REvIr8yQAAAIEA7uhhxnhmZK9T2OAIxYVYwA2gewzMx9HUTFf+vpBV7ZKiH+WTa7F9
  DIl8syV9xGHpiwMEZzME5XEbEYnZDngcSSPzlYAejCxS5EYcE7YVAFq2ZGDW9F+XQh5c9m
  RAzqr+fT+q1r7tM9flbt2CErLwDL5x0oFEFk1BzLdcoM0hTVEAAACBANMY3qeanPwcQrCL
  pEI8jfW+/uQ2D9z6bgyWq48AlAsu+Aq38SpeTFgVkDVxIAI8yaxeDii2dP3N0ceSzD/soS
  Z0W5zO4QCDC/sj1GRTtmKfckFa1MefZbtquKt9SFle7VID9ZMOwgw0n/LtyO+qXCl5Yk/K
  Y5UzKimeqYtffR1rAAAACmplbmtpbnMtY2k=
  -----END OPENSSH PRIVATE KEY-----

pinfracreg:
  id: pinfracreg.azurecr.io
  username: pinfracreg
  password: /==/Lm/=m+RhvbkqPGad=Egg/R2/jPXr

npm:
  id: npm.ramson.io
  username: jenkins
  password: RnI9sh264DHpultoODZIDogD